name: Benchmark Github Pages

# Must not run on pull requests if allowed to push github pages
on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  bench:
    - name: Run benchmark
      run: cargo bench --workspace | tee bench-output.txt
    - name: Process benchmark results
      uses: rhysd/github-action-benchmark@v1
      with:
        name: Rust Benchmark
        tool: 'cargo'
        output-file-path: bench-output.txt
        # Use personal access token instead of GITHUB_TOKEN due to https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869/highlight/false
        github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        auto-push: true
        # Show alert with commit comment on detecting possible performance regression
        alert-threshold: '130%'
        comment-on-alert: true
        fail-on-alert: true
        alert-comment-cc-users: '@nicomem,@tomatodelavegas'
