name: Benchmark Github Pages

# Must not run on pull requests if pushing github pages
on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  CARGO_BIN: cargo --locked --verbose

jobs:
  bench:
    - name: Run benchmark
      run: ${CARGO_BIN} bench --workspace | tee bench-output.txt
    - name: Process benchmark results
      uses: rhysd/github-action-benchmark@v1
      with:
        name: Rust Benchmark
        tool: 'cargo'
        output-file-path: bench-output.txt
        github-token: ${{ secrets.GITHUB_TOKEN }}
        # Show alert with commit comment on detecting possible performance regression
        alert-threshold: '130%'
        comment-on-alert: true
        fail-on-alert: true
        alert-comment-cc-users: '@nicomem,@tomatodelavegas'
        # Push and deplot Github pages branch automatically
        auto-push: true
