name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  CARGO_BIN: cargo --locked --workspace --verbose

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: ${CARGO_BIN} build
    - name: Run tests
      run: ${CARGO_BIN} test
    - name: Run benchmark
      run: ${CARGO_BIN} bench | tee bench-output.txt
    - name: Process benchmark results
      uses: rhysd/github-action-benchmark@v1
      with:
        name: Rust Benchmark
        tool: 'cargo'
        output-file-path: bench-output.txt
        github-token: ${{ secrets.GITHUB_TOKEN }}
        # Show alert with commit comment on detecting possible performance regression
        alert-threshold: '130%'
        comment-on-alert: true
        fail-on-alert: true
        alert-comment-cc-users: '@nicomem,@tomatodelavegas'
